kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: spring-alt-route
  namespace: phoonum-sl-dev
spec:
  to:
    kind: Service
    name: spring-alt-service
  tls: null
  port:
    targetPort: 8080
  alternateBackends: []
