apiVersion: v1
kind: Service
metadata:
  name: spring-alt-service
  namespace: phoonum-sl-dev
spec:
  selector:
    app: spring-alt
    deployment: spring-alt
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
